# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/solver/projects/zkdecrypto-lite

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/solver/projects/zkdecrypto-lite

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/solver/projects/zkdecrypto-lite/CMakeFiles /home/solver/projects/zkdecrypto-lite/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/solver/projects/zkdecrypto-lite/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named zkdecrypto-lite

# Build rule for target.
zkdecrypto-lite: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zkdecrypto-lite
.PHONY : zkdecrypto-lite

# fast build rule for target.
zkdecrypto-lite/fast:
	$(MAKE) -f CMakeFiles/zkdecrypto-lite.dir/build.make CMakeFiles/zkdecrypto-lite.dir/build
.PHONY : zkdecrypto-lite/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/zkdecrypto-lite.dir/build.make CMakeFiles/zkdecrypto-lite.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/zkdecrypto-lite.dir/build.make CMakeFiles/zkdecrypto-lite.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/zkdecrypto-lite.dir/build.make CMakeFiles/zkdecrypto-lite.dir/main.cpp.s
.PHONY : main.cpp.s

map.o: map.cpp.o
.PHONY : map.o

# target to build an object file
map.cpp.o:
	$(MAKE) -f CMakeFiles/zkdecrypto-lite.dir/build.make CMakeFiles/zkdecrypto-lite.dir/map.cpp.o
.PHONY : map.cpp.o

map.i: map.cpp.i
.PHONY : map.i

# target to preprocess a source file
map.cpp.i:
	$(MAKE) -f CMakeFiles/zkdecrypto-lite.dir/build.make CMakeFiles/zkdecrypto-lite.dir/map.cpp.i
.PHONY : map.cpp.i

map.s: map.cpp.s
.PHONY : map.s

# target to generate assembly for a file
map.cpp.s:
	$(MAKE) -f CMakeFiles/zkdecrypto-lite.dir/build.make CMakeFiles/zkdecrypto-lite.dir/map.cpp.s
.PHONY : map.cpp.s

message.o: message.cpp.o
.PHONY : message.o

# target to build an object file
message.cpp.o:
	$(MAKE) -f CMakeFiles/zkdecrypto-lite.dir/build.make CMakeFiles/zkdecrypto-lite.dir/message.cpp.o
.PHONY : message.cpp.o

message.i: message.cpp.i
.PHONY : message.i

# target to preprocess a source file
message.cpp.i:
	$(MAKE) -f CMakeFiles/zkdecrypto-lite.dir/build.make CMakeFiles/zkdecrypto-lite.dir/message.cpp.i
.PHONY : message.cpp.i

message.s: message.cpp.s
.PHONY : message.s

# target to generate assembly for a file
message.cpp.s:
	$(MAKE) -f CMakeFiles/zkdecrypto-lite.dir/build.make CMakeFiles/zkdecrypto-lite.dir/message.cpp.s
.PHONY : message.cpp.s

strarray.o: strarray.cpp.o
.PHONY : strarray.o

# target to build an object file
strarray.cpp.o:
	$(MAKE) -f CMakeFiles/zkdecrypto-lite.dir/build.make CMakeFiles/zkdecrypto-lite.dir/strarray.cpp.o
.PHONY : strarray.cpp.o

strarray.i: strarray.cpp.i
.PHONY : strarray.i

# target to preprocess a source file
strarray.cpp.i:
	$(MAKE) -f CMakeFiles/zkdecrypto-lite.dir/build.make CMakeFiles/zkdecrypto-lite.dir/strarray.cpp.i
.PHONY : strarray.cpp.i

strarray.s: strarray.cpp.s
.PHONY : strarray.s

# target to generate assembly for a file
strarray.cpp.s:
	$(MAKE) -f CMakeFiles/zkdecrypto-lite.dir/build.make CMakeFiles/zkdecrypto-lite.dir/strarray.cpp.s
.PHONY : strarray.cpp.s

unicode.o: unicode.cpp.o
.PHONY : unicode.o

# target to build an object file
unicode.cpp.o:
	$(MAKE) -f CMakeFiles/zkdecrypto-lite.dir/build.make CMakeFiles/zkdecrypto-lite.dir/unicode.cpp.o
.PHONY : unicode.cpp.o

unicode.i: unicode.cpp.i
.PHONY : unicode.i

# target to preprocess a source file
unicode.cpp.i:
	$(MAKE) -f CMakeFiles/zkdecrypto-lite.dir/build.make CMakeFiles/zkdecrypto-lite.dir/unicode.cpp.i
.PHONY : unicode.cpp.i

unicode.s: unicode.cpp.s
.PHONY : unicode.s

# target to generate assembly for a file
unicode.cpp.s:
	$(MAKE) -f CMakeFiles/zkdecrypto-lite.dir/build.make CMakeFiles/zkdecrypto-lite.dir/unicode.cpp.s
.PHONY : unicode.cpp.s

z340.o: z340.cpp.o
.PHONY : z340.o

# target to build an object file
z340.cpp.o:
	$(MAKE) -f CMakeFiles/zkdecrypto-lite.dir/build.make CMakeFiles/zkdecrypto-lite.dir/z340.cpp.o
.PHONY : z340.cpp.o

z340.i: z340.cpp.i
.PHONY : z340.i

# target to preprocess a source file
z340.cpp.i:
	$(MAKE) -f CMakeFiles/zkdecrypto-lite.dir/build.make CMakeFiles/zkdecrypto-lite.dir/z340.cpp.i
.PHONY : z340.cpp.i

z340.s: z340.cpp.s
.PHONY : z340.s

# target to generate assembly for a file
z340.cpp.s:
	$(MAKE) -f CMakeFiles/zkdecrypto-lite.dir/build.make CMakeFiles/zkdecrypto-lite.dir/z340.cpp.s
.PHONY : z340.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... zkdecrypto-lite"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... map.o"
	@echo "... map.i"
	@echo "... map.s"
	@echo "... message.o"
	@echo "... message.i"
	@echo "... message.s"
	@echo "... strarray.o"
	@echo "... strarray.i"
	@echo "... strarray.s"
	@echo "... unicode.o"
	@echo "... unicode.i"
	@echo "... unicode.s"
	@echo "... z340.o"
	@echo "... z340.i"
	@echo "... z340.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

